version: "3"

x-uffizzi:
  ingress:
    service: opentitan
    port: 7681

services:

  opentitan:
    image: "${OPENTITAN_IMAGE}" 
    ports:
    - "7700:7700"
    - "7681:7681"
    # entrypoint: ["/bin/bash", "-c"]
    # command: ["cd /home/dev && ttyd bash"]  
    entrypoint: ["/bin/bash"] 
    command: 
    - "-c"
    - "apt update && \ 
      apt install unzip -y && \ 
      wget 'https://github.com/$GHA_ACTOR/$GHA_REPO/archive/refs/heads/$GHA_BRANCH.zip'
      unzip $GHA_BRANCH.zip -d /home/dev/src && \
      ls && \
      cd /home/dev/src && \
      ttyd 
      "
    deploy:
      resources:
        limits:
          memory: 4000M

