version: "3"

x-uffizzi:
  ingress:
    service: opentitan
    port: 7681

services:

  opentitan:
    image: "${OPENTITAN_IMAGE}"
    volumes: 
      - .:/home/dev/src 
    ports:
    - "7700:7700"
    - "7681:7681"
    entrypoint: ["/bin/bash", "-c"]
    command: ["cd /home/dev && ttyd bash"]   
    deploy:
      resources:
        limits:
          memory: 4000M

# volumes:
#   .:
